import json
import logging
from typing import Dict, Any, List
import google.generativeai as genai
from llm_wrapper import FallbackGenerativeModel
from tools_agent import filter_tools_for_intent, get_gemini_tools

logger = logging.getLogger(__name__)

def execute_plan(plan: dict, system_prompt: str) -> str:
    """
    Takes a JSON plan generated by the Planner Agent and executes it step-by-step.
    Context from previous steps is carried forward.
    """
    steps = plan.get("steps", [])
    if not steps:
        return "No actionable steps were found in the plan."

    plan_summary = plan.get("plan_summary", "Executing task plan...")
    logger.info("Executing Plan: %s", plan_summary)
    
    # Store the results of each step so subsequent dependent steps can use the data
    step_results: Dict[int, str] = {}
    all_tools = get_gemini_tools()

    for step in sorted(steps, key=lambda x: x.get("step_number", 0)):
        step_number = step.get("step_number")
        target_tool = step.get("target_tool", "none").lower()
        instruction = step.get("instruction", "")
        depends_on = step.get("depends_on", [])
        
        logger.info("Running Step %s [Tool: %s]", step_number, target_tool)

        # Build context from dependencies
        context = ""
        if depends_on:
            context += "\nContext from previous steps:\n"
            for dep in depends_on:
                if dep in step_results:
                    context += f"Result of Step {dep}:\n{step_results[dep]}\n\n"

        # Determine which tools the LLM is allowed to use for this specific step
        active_tools = None
        if target_tool != "none":
            # Map the exact tool name (e.g. 'research_advanced') to a pseudo intent category to reuse the filter
            if "research" in target_tool:
                active_tools = filter_tools_for_intent(all_tools, "RESEARCH")
            elif "calendar" in target_tool:
                active_tools = filter_tools_for_intent(all_tools, "SCHEDULE")
            elif "code" in target_tool:
                active_tools = filter_tools_for_intent(all_tools, "CODE")
            elif "rag" in target_tool:
                active_tools = filter_tools_for_intent(all_tools, "RAG")
            
        step_model = FallbackGenerativeModel(
            "gemini-2.5-flash", "gemini-2.5-flash-lite",
            tools=active_tools if active_tools else None,
            system_instruction=system_prompt
        )

        chat = step_model.start_chat(
            history=[],
            enable_automatic_function_calling=bool(active_tools)
        )
        
        prompt = f"Execute this instruction exactly: {instruction}\n"
        if context:
            prompt += f"{context}\n"
            
        try:
            response = chat.send_message(prompt)
            result_text = response.text
            step_results[step_number] = result_text
            logger.info("Step %s completed.", step_number)
        except Exception as e:
            error_msg = f"Step {step_number} failed with error: {str(e)}"
            logger.error(error_msg)
            step_results[step_number] = error_msg
            break # Halt execution on error
            
    # Final aggregation: summarize the results for the user
    final_model = FallbackGenerativeModel("gemini-2.5-flash", "gemini-2.5-flash-lite", system_instruction=system_prompt)
    aggregation_prompt = f"The following complex plan was just executed:\nPlan: {plan_summary}\n\nHere are the raw results of each step:\n"
    for step_num, result in step_results.items():
        aggregation_prompt += f"--- Step {step_num} ---\n{result}\n\n"
        
    aggregation_prompt += "Please provide a final, cohesive, and user-friendly summary of everything that was accomplished."
    
    try:
        final_summary = final_model.generate_content(aggregation_prompt)
        return final_summary.text
    except Exception as e:
        return f"Execution finished, but failed to aggregate summary: {str(e)}"
